apiVersion: ovs.openstack.org/v1beta1
kind: OVS
metadata:
  name: openvswitch
spec:
  ovsContainerImage: "quay.io/tripleozedcentos9/openstack-ovn-base:current-tripleo"
  ovnContainerImage: "quay.io/tripleozedcentos9/openstack-ovn-controller:current-tripleo"
  external-ids:
    system-id: "random"
    ovn-bridge: "br-int"
    ovn-encap-type: "geneve"
  nicMappings:
    physnet1: enp2s0.100
    physnet2: enp2s0.200
